version: "3.7"

services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - express-app

  express-app:
    image: express-app
    ports:
      - "5000:5000"
